//
//  ChatStreamResult.swift
//  
//
//  Created by Sergii Kryvoblotskyi on 15/05/2023.
//

import Foundation

/// Represents a streamed chunk of a chat completion response returned
/// by the model, based on the provided input.
/// [Learn more](https://platform.openai.com/docs/guides/streaming-responses).
public struct ChatStreamResult: Codable, Equatable, Sendable {
    public struct Choice: Codable, Equatable, Sendable {
        public typealias FinishReason = ChatResult.Choice.FinishReason

        public struct ChoiceDelta: Sendable {
            public typealias Role = ChatQuery.ChatCompletionMessageParam.Role

            /// The contents of the chunk message.
            public let content: String?
            /// If the audio output modality is requested, this object contains data about the audio response from the model.
            public let audio: ChoiceDeltaAudio?

            /// The role of the author of this message.
            public let role: Self.Role?
            public let toolCalls: [Self.ChoiceDeltaToolCall]?

            /// Value for `reasoning` field in response.
            ///
            /// Provided by:
            /// - Gemini (in OpenAI compatibility mode)
            ///   https://github.com/MacPaw/OpenAI/issues/283#issuecomment-2711396735
            /// - OpenRouter
            internal let _reasoning: String?

            /// Value for `reasoning_content` field.
            ///
            /// Provided by:
            /// - Deepseek
            ///   https://api-docs.deepseek.com/api/create-chat-completion#responses
            internal let _reasoningContent: String?

            /// Reasoning content.
            ///
            /// Supported response fields:
            /// - `reasoning` (Gemini, OpenRouter)
            /// - `reasoning_content` (Deepseek)
            public var reasoning: String? {
                _reasoning ?? _reasoningContent
            }

            /// Value for `reasoning_details` field (OpenRouter/MiniMax format)
            /// Array of reasoning detail objects - uses [String: Any] to avoid coupling with app's AnyCodable
            /// wangqi added 2025-12-09
            internal let _reasoningDetails: [[String: Any]]?

            /// Reasoning details array (OpenRouter/MiniMax)
            public var reasoningDetails: [[String: Any]]? {
                _reasoningDetails
            }

            /// Media content from extended provider fields (images, etc.)
            public let images: [MediaContent]?

            public struct ChoiceDeltaAudio: Codable, Equatable, Sendable {

                /// Unique identifier for this audio response.
                public let id: String?
                /// Transcript of the audio generated by the model.
                public let transcript: String?
                /// The Unix timestamp (in seconds) for when this audio response will no longer be accessible on the server for use in multi-turn conversations.
                public let expiresAt: Int?
                /// Base64 encoded audio bytes generated by the model, in the format specified in the request.
                public let data: String?

                public enum CodingKeys: String, CodingKey {
                    case id
                    case transcript
                    case data
                    case expiresAt = "expires_at"
                }
            }

            public struct ChoiceDeltaToolCall: Codable, Equatable, Sendable {

                public let index: Int?
                /// The ID of the tool call.
                public let id: String?
                /// The function that the model called.
                public let function: Self.ChoiceDeltaToolCallFunction?
                /// The type of the tool. Currently, only function is supported.
                public let type: String?
                /// Extra content from provider-specific extensions (e.g., Gemini's thought_signature)
                /// wangqi 2025-12-24
                public let extraContent: [String: Any]?

                public init(
                    index: Int,
                    id: String? = nil,
                    function: Self.ChoiceDeltaToolCallFunction? = nil,
                    extraContent: [String: Any]? = nil
                ) {
                    self.index = index
                    self.id = id
                    self.function = function
                    self.type = "function"
                    self.extraContent = extraContent
                }

                /// Extract thought_signature from Gemini's nested structure
                /// Returns the signature if found in extra_content.google.thought_signature
                /// wangqi 2025-12-24
                public var thoughtSignature: String? {
                    guard let extraContent = extraContent,
                          let google = extraContent["google"] as? [String: Any],
                          let signature = google["thought_signature"] as? String else {
                        return nil
                    }
                    return signature
                }

                // Custom Codable implementation for extra_content handling
                // wangqi 2025-12-24
                public enum CodingKeys: String, CodingKey {
                    case index
                    case id
                    case function
                    case type
                    case extraContent = "extra_content"
                }

                public init(from decoder: Decoder) throws {
                    let container = try decoder.container(keyedBy: CodingKeys.self)
                    self.index = try container.decodeIfPresent(Int.self, forKey: .index)
                    self.id = try container.decodeIfPresent(String.self, forKey: .id)
                    self.function = try container.decodeIfPresent(ChoiceDeltaToolCallFunction.self, forKey: .function)
                    self.type = try container.decodeIfPresent(String.self, forKey: .type) ?? "function"

                    // Decode extra_content using JSONValue
                    if let jsonExtraContent = try container.decodeIfPresent([String: JSONValue].self, forKey: .extraContent) {
                        self.extraContent = jsonExtraContent.mapValues { $0.toAny() }
                    } else {
                        self.extraContent = nil
                    }
                }

                public func encode(to encoder: Encoder) throws {
                    var container = encoder.container(keyedBy: CodingKeys.self)
                    try container.encodeIfPresent(index, forKey: .index)
                    try container.encodeIfPresent(id, forKey: .id)
                    try container.encodeIfPresent(function, forKey: .function)
                    try container.encodeIfPresent(type, forKey: .type)

                    // Encode extra_content using JSONValue
                    if let extraContent = extraContent {
                        let jsonExtraContent = extraContent.mapValues { JSONValue.from($0) }
                        try container.encode(jsonExtraContent, forKey: .extraContent)
                    }
                }

                public struct ChoiceDeltaToolCallFunction: Codable, Equatable, Sendable {

                    /// The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.
                    public let arguments: String?
                    /// The name of the function to call.
                    public let name: String?

                    public init(
                        arguments: String? = nil,
                        name: String? = nil
                    ) {
                        self.arguments = arguments
                        self.name = name
                    }
                }
            }

            // Databricks Model Serving (gpt-oss models) streams delta.content as an ARRAY of
            // typed parts instead of a plain string, e.g.
            //   "content":[{"type":"reasoning","summary":[{"type":"summary_text","text":"..."}]},
            //              {"type":"text","text":"..."}]
            // Tolerant part decoder so streamed text/reasoning is extracted instead of the whole
            // chunk failing to decode (which silently dropped the assistant's reply).
            // wangqi modified 2026-06-01
            struct ChoiceDeltaContentPart: Decodable {
                let type: String?
                let text: String?
                let summary: [SummaryPart]?

                struct SummaryPart: Decodable {
                    let text: String?
                    enum CodingKeys: String, CodingKey { case text }
                    init(from decoder: Decoder) throws {
                        let c = try decoder.container(keyedBy: CodingKeys.self)
                        text = try c.decodeIfPresent(String.self, forKey: .text)
                    }
                }

                enum CodingKeys: String, CodingKey { case type, text, summary }
                init(from decoder: Decoder) throws {
                    let c = try decoder.container(keyedBy: CodingKeys.self)
                    type = try c.decodeIfPresent(String.self, forKey: .type)
                    text = try c.decodeIfPresent(String.self, forKey: .text)
                    summary = try c.decodeIfPresent([SummaryPart].self, forKey: .summary)
                }

                /// Visible text: parts of type "text" (or untyped parts that carry text).
                var textValue: String? {
                    guard type == "text" || type == nil else { return nil }
                    return text
                }
                /// Reasoning text: type "reasoning" parts, preferring nested summary_text.
                var reasoningValue: String? {
                    guard type == "reasoning" else { return nil }
                    let joinedSummary = (summary ?? []).compactMap { $0.text }.joined()
                    return joinedSummary.isEmpty ? text : joinedSummary
                }
            }

            public enum CodingKeys: String, CodingKey {
                case content
                case audio
                case role
                case toolCalls = "tool_calls"
                case _reasoning = "reasoning"
                case _reasoningContent = "reasoning_content"
                case _reasoningDetails = "reasoning_details"
                case images
            }
            
            public init(from decoder: Decoder) throws {
                let container = try decoder.container(keyedBy: CodingKeys.self)

                // Decode standard fields.
                // content is normally a String, but Databricks gpt-oss streams it as a typed-part
                // array; decode both shapes so the chunk never fails wholesale. A null/absent
                // content decodes as nil via the String branch (decodeIfPresent succeeds with nil),
                // so only a genuine array falls through to the part decoder.
                // wangqi modified 2026-06-01
                var arrayReasoning: String? = nil
                if let stringContent = try? container.decodeIfPresent(String.self, forKey: .content) {
                    content = stringContent
                } else if let parts = try? container.decodeIfPresent([ChoiceDeltaContentPart].self, forKey: .content) {
                    let joinedText = (parts ?? []).compactMap { $0.textValue }.joined()
                    content = joinedText.isEmpty ? nil : joinedText
                    let joinedReasoning = (parts ?? []).compactMap { $0.reasoningValue }.joined()
                    arrayReasoning = joinedReasoning.isEmpty ? nil : joinedReasoning
                } else {
                    content = nil
                }
                audio = try container.decodeIfPresent(ChoiceDeltaAudio.self, forKey: .audio)
                role = try container.decodeIfPresent(Role.self, forKey: .role)
                toolCalls = try container.decodeIfPresent([ChoiceDeltaToolCall].self, forKey: .toolCalls)
                // Reasoning may arrive via the dedicated field OR (gpt-oss) inside the content array.
                // wangqi modified 2026-06-01
                _reasoning = (try container.decodeIfPresent(String.self, forKey: ._reasoning)) ?? arrayReasoning
                _reasoningContent = try container.decodeIfPresent(String.self, forKey: ._reasoningContent)

                // Decode reasoning_details using JSONValue (wangqi 2025-12-09)
                if let jsonDetails = try container.decodeIfPresent([[String: JSONValue]].self, forKey: ._reasoningDetails) {
                    _reasoningDetails = jsonDetails.map { dict in
                        dict.mapValues { $0.toAny() }
                    }
                } else {
                    _reasoningDetails = nil
                }

                // Decode images using MediaContentFactory
                images = MediaContentFactory.decodeMediaContent(from: container, forKey: .images)
            }

            // wangqi 2025-12-09: Custom encode() for Codable conformance
            public func encode(to encoder: Encoder) throws {
                var container = encoder.container(keyedBy: CodingKeys.self)
                try container.encodeIfPresent(content, forKey: .content)
                try container.encodeIfPresent(audio, forKey: .audio)
                try container.encodeIfPresent(role, forKey: .role)
                try container.encodeIfPresent(toolCalls, forKey: .toolCalls)
                try container.encodeIfPresent(_reasoning, forKey: ._reasoning)
                try container.encodeIfPresent(_reasoningContent, forKey: ._reasoningContent)
                // Encode reasoning_details using JSONValue
                if let details = _reasoningDetails {
                    let jsonDetails = details.map { dict in
                        dict.mapValues { JSONValue.from($0) }
                    }
                    try container.encode(jsonDetails, forKey: ._reasoningDetails)
                }
                // Note: images are not encoded - they are only decoded from extended fields
            }
        }

        /// The index of the choice in the list of choices.
        public let index: Int
        /// A chat completion delta generated by streamed model responses.
        public let delta: Self.ChoiceDelta
        /// The reason the model stopped generating tokens.
        /// This will be `stop` if the model hit a natural stop point or a provided stop sequence, `length` if the maximum number of tokens specified in the request was reached, `content_filter` if content was omitted due to a flag from our content filters, `tool_calls` if the model called a tool, or `function_call` (deprecated) if the model called a function.
        public let finishReason: FinishReason?
        /// Log probability information for the choice.
        public let logprobs: Self.ChoiceLogprobs?

        public struct ChoiceLogprobs: Codable, Equatable, Sendable {
            /// A list of message content tokens with log probability information.
            public let content: [Self.ChatCompletionTokenLogprob]?

            public struct ChatCompletionTokenLogprob: Codable, Equatable, Sendable {
                /// The token.
                public let token: String
                /// A list of integers representing the UTF-8 bytes representation of the token. Useful in instances where characters are represented by multiple tokens and their byte representations must be combined to generate the correct text representation. Can be null if there is no bytes representation for the token.
                public let bytes: [Int]?
                /// The log probability of this token.
                public let logprob: Double
                /// List of the most likely tokens and their log probability, at this token position. In rare cases, there may be fewer than the number of requested top_logprobs returned.
                public let topLogprobs: [Self.TopLogprob]?

                public struct TopLogprob: Codable, Equatable, Sendable {
                    /// The token.
                    public let token: String
                    /// A list of integers representing the UTF-8 bytes representation of the token. Useful in instances where characters are represented by multiple tokens and their byte representations must be combined to generate the correct text representation. Can be null if there is no bytes representation for the token.
                    public let bytes: [Int]?
                    /// The log probability of this token.
                    public let logprob: Double
                }

                public enum CodingKeys: String, CodingKey {
                    case token
                    case bytes
                    case logprob
                    case topLogprobs = "top_logprobs"
                }
            }
        }

        public enum CodingKeys: String, CodingKey {
            case index
            case delta
            case finishReason = "finish_reason"
            case logprobs
        }
    }

    /// A unique identifier for the chat completion. Each chunk has the same ID.
    public let id: String

    /// The object type, which is always `chat.completion.chunk`.
    public let object: String

    /// The Unix timestamp (in seconds) of when the chat completion was created. Each chunk has the same timestamp.
    public let created: TimeInterval

    /// The model to generate the completion.
    public let model: String
    
    /// A list of chat completion choices. Can contain more than one element if `n` is greater than 1.
    /// Can also be empty for the last chunk if you set `stream_options: {"include_usage": true}`.
    public let choices: [Choice]
    
    /// This fingerprint represents the backend configuration that the model runs with.
    /// Can be used in conjunction with the `seed` request parameter to understand when backend changes
    /// have been made that might impact determinism.
    ///
    /// Note: Even though [API Reference - The chat completion chunk object - system_fingerprint](https://platform.openai.com/docs/api-reference/chat-streaming/streaming#chat-streaming/streaming-system_fingerprint) declares the type as `string` (aka non-optional) - the response chunk may not contain the value, so we have had to make it optional `String?` in the Swift type
    /// See https://github.com/MacPaw/OpenAI/issues/331 for more details on such a case.
    public let systemFingerprint: String?
    
    /// Usage statistics for the completion request.
    public let usage: ChatResult.CompletionUsage?
    
    /// Specifies the latency tier to use for processing the request. This parameter is relevant
    /// for customers subscribed to the scale tier service:
    ///
    /// - If set to 'auto', and the Project is Scale tier enabled, the system will utilize scale tier credits until they are exhausted.
    /// - If set to 'auto', and the Project is not Scale tier enabled, the request will be processed using the default service tier with a lower uptime SLA and no latency guarantee.
    /// - If set to 'default', the request will be processed using the default service tier with a lower uptime SLA and no latency guarantee.
    /// - If set to 'flex', the request will be processed with the Flex Processing service tier.
    ///   [Learn more](https://platform.openai.com/docs/guides/flex-processing).
    /// - When not set, the default behavior is 'auto'.
    ///
    /// When this parameter is set, the response body will include the `service_tier` utilized.
    public let serviceTier: ServiceTier?
    
    /// A list of citations for the completion.
    ///
    /// - Note: the field is not a part of OpenAI API but is used by other providers
    public let citations: [String]?
    
    /// Optionally store the "provider" field from the JSON.
    // wangqi added it for OpenRouter 2025-04-07
    public let provider: String?

    public enum CodingKeys: String, CodingKey {
        case id
        case object
        case created
        case model
        case citations
        case choices
        case systemFingerprint = "system_fingerprint"
        case usage
        case serviceTier = "service_tier"
        case provider
    }
    
    public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        //wangqi modified 2025-04-07. Set default ParsingOptions
        let parsingOptions = decoder.userInfo[.parsingOptions] as? ParsingOptions ?? [.fillRequiredFieldIfKeyNotFound, .fillRequiredFieldIfValueNotFound]
        
        self.id = try container.decodeString(forKey: .id, parsingOptions: parsingOptions)
        self.object = try container.decodeString(forKey: .object, parsingOptions: parsingOptions)
        self.created = try container.decode(TimeInterval.self, forKey: .created)
        self.model = try container.decodeString(forKey: .model, parsingOptions: parsingOptions)
        self.citations = try container.decodeIfPresent([String].self, forKey: .citations)
        self.choices = try container.decode([ChatStreamResult.Choice].self, forKey: .choices)
        self.systemFingerprint = try container.decodeIfPresent(String.self, forKey: .systemFingerprint)
        
        // Even though API Reference declares that usage field should be either informative or null: https://platform.openai.com/docs/api-reference/chat/create#chat-create-stream_options
        // In some cases it can be present, but empty: https://github.com/MacPaw/OpenAI/issues/338
        //
        // To make things simpler, we're not going to check the correctnes of payload before trying to decode
        // We're just going to ignore all the errors here by using optional try and fallback to nil `usage`
        self.usage = try? container.decodeIfPresent(ChatResult.CompletionUsage.self, forKey: .usage)
        self.serviceTier = try container.decodeIfPresent(ServiceTier.self, forKey: .serviceTier)
        self.provider = try container.decodeIfPresent(String.self, forKey: .provider)
    }
}

// MARK: - ChoiceDelta Codable Conformance (wangqi 2025-12-09)
extension ChatStreamResult.Choice.ChoiceDelta: Codable {}

// MARK: - ChoiceDelta Equatable Conformance (wangqi 2025-12-09)
extension ChatStreamResult.Choice.ChoiceDelta: Equatable {
    public static func == (lhs: ChatStreamResult.Choice.ChoiceDelta, rhs: ChatStreamResult.Choice.ChoiceDelta) -> Bool {
        guard lhs.content == rhs.content,
              lhs.audio == rhs.audio,
              lhs.role == rhs.role,
              lhs.toolCalls == rhs.toolCalls,
              lhs._reasoning == rhs._reasoning,
              lhs._reasoningContent == rhs._reasoningContent else {
            return false
        }

        // Compare _reasoningDetails by converting to JSON (since [String: Any] isn't Equatable)
        if lhs._reasoningDetails == nil && rhs._reasoningDetails == nil {
            return true
        }
        guard let lhsDetails = lhs._reasoningDetails,
              let rhsDetails = rhs._reasoningDetails else {
            return false
        }
        guard JSONSerialization.isValidJSONObject(lhsDetails),
              JSONSerialization.isValidJSONObject(rhsDetails) else {
            return false
        }
        let lhsData = try? JSONSerialization.data(withJSONObject: lhsDetails)
        let rhsData = try? JSONSerialization.data(withJSONObject: rhsDetails)

        // Note: images are not compared since they are optional media extensions
        return lhsData == rhsData
    }
}

// MARK: - ChoiceDeltaToolCall Equatable Conformance (wangqi 2025-12-24)
extension ChatStreamResult.Choice.ChoiceDelta.ChoiceDeltaToolCall {
    public static func == (lhs: ChatStreamResult.Choice.ChoiceDelta.ChoiceDeltaToolCall, rhs: ChatStreamResult.Choice.ChoiceDelta.ChoiceDeltaToolCall) -> Bool {
        guard lhs.index == rhs.index,
              lhs.id == rhs.id,
              lhs.function == rhs.function,
              lhs.type == rhs.type else {
            return false
        }

        // Compare extraContent by converting to JSON (since [String: Any] isn't Equatable)
        if lhs.extraContent == nil && rhs.extraContent == nil {
            return true
        }
        guard let lhsExtra = lhs.extraContent,
              let rhsExtra = rhs.extraContent else {
            return false
        }
        guard JSONSerialization.isValidJSONObject(lhsExtra),
              JSONSerialization.isValidJSONObject(rhsExtra) else {
            return false
        }
        let lhsData = try? JSONSerialization.data(withJSONObject: lhsExtra)
        let rhsData = try? JSONSerialization.data(withJSONObject: rhsExtra)
        return lhsData == rhsData
    }
}
