//
//  ImagesResult.swift
//  
//
//  Created by Sergii Kryvoblotskyi on 02/04/2023.
//

import Foundation

/// Returns a list of image objects.
public struct ImagesResult: Codable, Equatable, Sendable {

    public let created: TimeInterval
    public let data: [Self.Image]

    /// Represents the url or the content of an image generated by the OpenAI API.
    public struct Image: Codable, Equatable, Sendable {

        /// The base64-encoded JSON of the generated image, if response_format is b64_json
        public let b64Json: String?
        /// The prompt that was used to generate the image, if there was any revision to the prompt.
        public let revisedPrompt: String?
        /// The URL of the generated image, if response_format is url (default).
        public let url: String?

        public enum CodingKeys: String, CodingKey {
            case b64Json = "b64_json"
            case revisedPrompt = "revised_prompt"
            case url
        }
        
        //wangqi 2025-03-29
        public init(b64Json: String? = nil, revisedPrompt: String? = nil, url: String? = nil) {
            self.b64Json = b64Json
            self.revisedPrompt = revisedPrompt
            self.url = url
        }
    }
    
    //wangqi 2025-03-29
    public init(created: TimeInterval = Date().timeIntervalSince1970, data: [ImagesResult.Image] = []) {
        self.created = created
        self.data = data
    }
}
